# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6956389003db5853dc4c7858b28b9f272c2690cc67c96055744194a3e2ae68d0c8534d0365eb4f4be2685dd9be3c358d449f292fa8eda33d7edb996ac7498fb8

test:
  secret_key_base: 95bb3c17445da0997fbba8b24a03d19aca202f7a5c0c862ea56c99135dbb46569ed2c00d2a6ada458c0363fba1fa68dcff258d7d33d83003a20a8565c15ce739

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
